// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cFMgawIzsoSTuKLY4G8vcWvsY6POByg',
    appId: '1:357239775641:web:ad45a7293fa459ee567308',
    messagingSenderId: '357239775641',
    projectId: 'matching-app-2025-bf3e3',
    authDomain: 'matching-app-2025-bf3e3.firebaseapp.com',
    storageBucket: 'matching-app-2025-bf3e3.firebasestorage.app',
    measurementId: 'G-06Z75BRK3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFHY3_ohfZvzQLQRNjFZHWSixXpjk5W8',
    appId: '1:357239775641:android:a4fc274d4b52ebf3567308',
    messagingSenderId: '357239775641',
    projectId: 'matching-app-2025-bf3e3',
    storageBucket: 'matching-app-2025-bf3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnskySwoZtjFhW6mBQB1U99vGyv9Ys90',
    appId: '1:357239775641:ios:2559491c623452b5567308',
    messagingSenderId: '357239775641',
    projectId: 'matching-app-2025-bf3e3',
    storageBucket: 'matching-app-2025-bf3e3.firebasestorage.app',
    iosBundleId: 'com.app.matching.matchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOnskySwoZtjFhW6mBQB1U99vGyv9Ys90',
    appId: '1:357239775641:ios:2559491c623452b5567308',
    messagingSenderId: '357239775641',
    projectId: 'matching-app-2025-bf3e3',
    storageBucket: 'matching-app-2025-bf3e3.firebasestorage.app',
    iosBundleId: 'com.app.matching.matchingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cFMgawIzsoSTuKLY4G8vcWvsY6POByg',
    appId: '1:357239775641:web:263fc4f78b296d73567308',
    messagingSenderId: '357239775641',
    projectId: 'matching-app-2025-bf3e3',
    authDomain: 'matching-app-2025-bf3e3.firebaseapp.com',
    storageBucket: 'matching-app-2025-bf3e3.firebasestorage.app',
    measurementId: 'G-QQTX9F7V2H',
  );
}
